CONSUMER_KEY = "TWITTERAPPLICATIONCONSUMERKEY"
CONSUMER_SECRET = "TWITTERAPPLICATIONCONSUMERSECRET"
ACCESS_TOKEN = "TWITTERAPPLICATIONACCESSTOKEN"
ACCESS_SECRET = "TWITTERAPPLICATIONACCESSTOKENSECRET"